app/api.py, tests/tests.py
Resolves #40
While refactoring the XOSAPI class, I managed to introduce a bug that mutated the default params. This PR fixes that.
* None
Testing this completely requires running an update which takes a long time (~3 hours). So you can either:
1. Revert the changes to `api.py` by removing `.copy()` references
1. Run the tests to see them fail (the default params were mutated to include `date_modified__gte`): `docker exec -it api make test`
or
1. Start the base environment: `cd development` and `docker-compose -f docker-compose-base.yml up`
1. Run an update: `docker exec -it api ash` and `UPDATE_WORKS=true python -u -m app.api`
1. After the run has complete, note that the `/works/` index page shows the full `42664` works: http://localhost:8081/works/
~- [ ] …
=> #40 Fix XOSAPI default params mutation bug

app/api.py, tests/tests.py
Resolves #41
When deleting unpublished Works metadata from the filesystem, also delete it from the search index.
* None
1. Start your environment: `cd development` and `docker-compose up`
1. Find a record that's indexed locally: http://localhost:8081/search/?query=xos
1. Manually delete it: `docker exec -it api ash` and `python3` and `from app.api import Search` and `Search().delete('works', 'id')`
1. Note that it no longer appears in search results: http://localhost:8081/search/?query=xos
=> #41 Delete unpublished Works from the search index

app/api.py, tests/tests.py
Resolves #44
Handle attempts to delete elasticsearch records that have already been deleted and so return a `404` from elasticsearch.
* None
1. Start your environment: `docker-compose up`
1. Run a python shell: `docker exec -it api python`
1. Try deleting a search record that doesn't exist: `from app.api import Search` and `Search().delete('works', '1')`
1. Note that it returns `False` and doesn't throw an exception
=> #44 Handle attempts to delete elasticsearch records that have already been deleted

README.md
Resolves #46
As a researcher I'd like to be able to compare TSV fields with old ACMI Collection data.
* None
1. Check the links work and the language sounds okay
=> #46 Add a link to the deprecated Collections TSV file

.github/workflows/main.yml
Resolves #50
Fix deprecated dry-run argument in kubectl command.
* None
1. Replace `BUILD_NUMBER` with `681db02973c9fdb0324f46df8cde80081aaf97ca` in `kubernetes/api.yml`
1. Try a dry run: `kubectl apply --namespace=xos-api-stg -f kubernetes/api.yml --dry-run=client`
=> #50 Update deprecated --dry-run argument from true to client

development/docker-compose.yml
Resolves #48
Upgrade elasticsearch development container to `v7.16.1`
* None
1. Build the development environment `docker-compose up --build`
1. Check the search still returns expected results: http://localhost:8081/search/?query=xos
=> #48 Upgrade elasticsearch development container to v7.16.1

requirements/base.txt
Resolves #56
Pin elasticsearch to v7 to avoid the failing build.
* None
1. See this build passes
1. See the search still works locally: `cd development` and `docker-compose up --build` and http://localhost:8081/search/?query=xos
~- [ ] Changelog has been updated if necessary~
=> #56 Pin elasticsearch to v7

app/api.py, tests/tests.py
Resolves #59
The spreadsheet exporter requires fields to have custom logic for them to be exported in a useful format. Let's add the recently added XOS Works API fields.
* None
1. Start your environment: `cd development` and `docker-compose -f docker-compose-base.yml up`
1. Re-create the TSV and note the two new fields added to the end of `app/tsv/works.tsv`
```bash
$ docker exec -it api ash
$ python
> from app.api import XOSAPI
> x = XOSAPI()
> x.generate_tsv('works')
```
=> #59 Add missing fields to the TSV exporter

scripts/update-api.sh
Resolves #53
When the updater attempts to run it sometimes fails because it doesn't have the `main` branch in its local clone.
* None
1. Ash into the staging pod: `kubectl exec -it -n xos-api-stg xos-api-78b47b6f8-cxw4g ash`
1. Note that you can't `git checkout main`
1. Run `git pull`
1. Note that you can `git checkout main`
=> #53 Updater fails switching to main branch

scripts/update-api.sh
Resolves #52
When trying to `git push` large changes of the ~45,000 JSON files, git runs out of memory.
Let's attempt to solve this by using this method: https://stackoverflow.com/a/36189893
* None
1. Bash into a pod after the updater fails and run `git fetch --unshallow`
1. Note that you can now successfully `git push` that night's commit
=> #52 Investigate the updater's git resource use

app/api.py, scripts/update-api.sh, tests/tests.py
Resolves #66
It appears there's a Work (or series of Works) in XOS that are taking longer than 30 seconds to render on the API. Let's add `params` to the debug output, increase the timeout to 60 seconds, and raise the right exception if it continues to fail.
* None
1. Disconnect from the VPN
1. Set `XOS_TIMEOUT` to `'3'` seconds
1. Start the API: `cd development` and `docker-compose up`
1. Connect to the api: `docker exec -it api ash`
1. Run the updater: `CRON_UPDATER=true ./scripts/update-api.sh`
1. Note that after 3 attempts it raises a timeout exception
=> #66 Handle XOS timeout

scripts/update-api.sh
Resolves #68
Attempt 1 didn't work, so let's try setting a larger space for command arguments.
* None
1. None
=> #68 Handle git argument list too long - attempt 2

.github/workflows/main.yml, scripts/update-api.sh
Resolves #71
The ACMI API updater has been failing with the following error:
```python
Starting ACMI public API updater...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>
```
* None
1. Note this branch's GitHub Actions still pass
1. After merging, note the updater updates nightly again
=> #71 Fix not on a branch error

.github/workflows/main.yml, .pylintrc, tests/tests.py
Resolves #79
Our build is failing because of Pylint updates, so let's update our codebase to get it to pass again.
Add a links to the relevant design files or leave as none.
* None
1. Note this branch passes
=> #79 Update syntax for Pylint

scripts/update-api.sh
Resolves #88
To avoid crashing when trying to run a diff on the updates after the updater script runs, let's fetch the whole history.
Add a list of steps required to test the feature.
1. Note the updater runs without failing on `git push`
=> #88 Fetch the whole history before updating

.github/workflows/main.yml
Resolves #94
Let's unpin GitHub Actions to avoid deprecations.
* None
1. Note the GitHub Action still runs
=> #94 Upgrade GitHub Actions

requirements/base.txt
Resolves #97
Running `make test` results in the error:
```bash
File "/usr/local/lib/python3.12/site-packages/pytest_flask/fixtures.py", line 6, in <module>
from flask import _request_ctx_stack
ImportError: cannot import name '_request_ctx_stack' from 'flask' (/usr/local/lib/python3.12/site-packages/flask/__init__.py)
make: *** [Makefile:34: test] Error 1
```
* None
1. Re-build: `make build`
1. Run tests: `docker exec -it api make linttest`
=> #97 Pin Flask to v2.x until Pytest updates

.github/workflows/main.yml, Makefile, development/docker-compose-base.yml, development/docker-compose.yml
Resolves #104
Let's update the deprecated docker syntax to fix the build.
* None
1. Note the build is fixed again.
1. Note you can still build `make build`
=> #104 Update docker syntax

scripts/entrypoint.sh
Resolves #112
Small bug fix for the suggestions API database to avoid loading an old database at boot.
* None
1. Re-build the app: `make build`
1. Note your database matches `development`: https://api-stg.acmi.net.au/suggestions/
=> #112 Remove old suggestions database at boot

requirements/base.txt
Resolves #114
Let's get ICT to upgrade our ElasticCloud service to elasticsearch v9.
* None
1. Build with `make build`
1. Note you can search again: http://localhost:8081/search/?query=hello
=> #114 Pin elasticsearch to v8 until we upgrade our cloud service to v9

development/docker-compose.yml, requirements/base.txt
Resolves #116
Upgrade elasticsearch to `v9`.
* None
1. Re-build your containers with `DEBUG=true` in your `config.env`: `make build`
1. Connect to a Python shell: `docker exec -it api python`
1. Inside that shell run: `from app.api import Search` and `Search().update_index('works')`
=> #116 Upgrade to elasticsearch v9
